### ISSUE TITLE
Implement member info change API

### ISSUE THREAD

**Issue by JBoss925** [cornell-dti/idol-backend#7]
Implement the form that allows a user to change their user information from the website (as seen [here](https://www.cornelldti.org/team/)).

Assumptions:

- The frontend will request the backend to get the current info for a user
- The frontend will submit a new version to the backend (backend should only update fields provided)

First Steps:

- Model this information in the database
- Populate the database with the user information from the JSON files found [here](https://github.com/cornell-dti/nova.cornelldti.org/tree/master/packages/website/data/members).

We want the user to be able to:

- Change their about me description
- Update their past team work (as well as ensure we have their current team from the DB on there)
- Update their role based on what we have in the database
- Add reference links (website, github, etc.)
- Edit basic info (Major, hometown, graduation date, etc.)

**Comment by SamChou19815** [comment]
I think it it implemented now.
